project: 
  type: book
  render:
    - "*.*"
    - "!notebooks/*.ipynb"

execute:
  freeze: auto

date: now
date-format: "YYYY-MM-DDTHH:mm"

book:
  title: "Hyperspectral products for fisheries"
  subtitle: "Hyperspectral products for fisheries and aquaculture"
  favicon: images/favicon.png
  site-url: https://ocean-satellite-tools.github.io/fish-pace
  repo-url: https://github.com/ocean-satellite-tools/fish-pace
  repo-actions: [edit, issue, source]
  page-footer: |
    <img src="https://raw.githubusercontent.com/nmfs-opensci/assets/main/logo/nmfs-opensci-logo3.png" 
         alt="NMFS OpenSci" style="width:200px"><br />
    Fish-PACE HackWeek (2025)

  chapters:
    - index.qmd
    - part: "Overview"
      chapters:
        - content/1_introduction.md
        - content/1_hyperspectral.md
        - content/1_which_satellites.md
    - part: "Hyperspectral products"
      chapters:
        - content/2__products.md
        - content/2_chla.qmd
        - content/2_phytoplankton_carbon.qmd
        - content/2_kd.md
        - content/2_aph.md
        - content/2_adg.md
        - content/2_bbp.md
        - content/2_par.md
        - content/2_rrs.qmd
        - href: content/2_avw.qmd
          text: "Apparent Visible Wavelength"

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html
    number-sections: true
    fig-numbering: true
    fig-caption-location: bottom
    number-depth: 1

filters:
  - include-files.lua
  - quarto
