---
title: Introduction
author: Ryan Vandermeulen
---

The sun emits electromagnetic radiation that hits the Earth, and all of life on this planet depends on just
a tiny portion of the electromagnetic spectrum - the colors of the rainbow (‘visible’ light). These are the
specific wavelengths (400 -700 nm) by which plants on Earth photosynthesize and give us oxygen that we
breathe. As this visible light hits the surface of the ocean and goes into the water, only one of two things
can happen to that light - the light can either be scattered, or it can be absorbed by various constituents
in the seawater. Pure water naturally absorbs more red light, leaving blue light to be scattered back to
our eyes, and it is why the deep ocean appears blue. Conversely, other materials in the water – algae,
dissolved organic material, dying or dead plant cells, floating seaweed, pollutants, suspended sediments
from land, among other things - each uniquely absorb different amounts and types (wavelengths) of light,
creating a color palette that we sense from discrete measurements of light from satellite sensors.